version: '3.1'
services:

    postgis:
        image: postgis/postgis:14-3.2-alpine
        container_name: postgis
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: postgis
            PGUSER: postgis
            POSTGRES_USER: postgis
            POSTGRES_DATABSE: postgis
        volumes:
            - ./enableExt.sql:/docker-entrypoint-initdb.d/enableExt.sql:ro
            - ./database/testData.tif:/home/database/testData.tif:ro
            - ./database/generatedData:/home/database/generatedData

    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@yopmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        links:
            - postgis

# raster2pgsql -F -I -C -t 10000x10000  /home/database/testData.tif public.world > /home/database/generatedData/out.sql